---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastify-basic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:asdutoit/test-docker.git
    targetRevision: HEAD
    path: kubernetes/fastify/environments/dev/fastify-basic
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
