apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-basic
  namespace: backend
  labels:
    app: fastify-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastify-basic
  template:
    metadata:
      labels:
        editor: vscode
        app: fastify-basic
        prometheus: main
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: fastify-basic
          image: asdutoit/fastify-basic:1.20.11
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 3001
              scheme: HTTP
            initialDelaySeconds: 10
          ports:
            - name: http
              containerPort: 3001
            # - name: http-metrics
            #   containerPort: 3001
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "400m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "800m"
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: fastify-basic-secrets
                  key: REDIS_URL
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastify-basic-secrets
                  key: REDIS_USERNAME
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastify-basic-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: fastify-basic-config
                  key: REDIS_PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: fastify-basic-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: fastify-basic-config
                  key: PORT
            - name: ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: fastify-basic-config
                  key: ADDRESS
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: fastify-basic-config
                  key: LOKI_URL
            - name: LOKI_PORT
              valueFrom:
                configMapKeyRef:
                  name: fastify-basic-config
                  key: LOKI_PORT
      imagePullSecrets:
        - name: dockerconfigjson
