---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fastify-basic
  namespace: backend
  labels:
    prometheus: main
spec:
  namespaceSelector: # This is optional since we are creating the PodMonitor in the same namespace as the app we want to monitor.
    matchNames:
      - backend
  selector:
    matchLabels:
      app: fastify-basic
  podMetricsEndpoints:
    - port: http
      path: /metrics
