apiVersion: v1
kind: Service
metadata:
  name: fastify-basic
  namespace: backend
spec:
  selector:
    app: fastify-basic
  ports:
    - protocol: TCP
      port: 3002 # External port on the service
      targetPort: 3002 # Port on the pod
      nodePort: 30100
  type: NodePort # You can use ClusterIP, NodePort, or LoadBalancer depending on your requirements
