global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "fastify-basic"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["fastify-basic:3002"]
      - labels:
          group: "production"
          type: "backend"
  - job_name: "monitoring/prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "monitoring/grafana"
    static_configs:
      - targets: ["grafana:3000"]
