---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-config
  namespace: observability
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: loki-ingester
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      max_transfer_retries: 0
    schema_config:
      configs:
        - from: 2021-09-01
          store: boltdb
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 168h
    storage_config:
      boltdb:
        directory: /data/loki/index
    storage_config:
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 72h
