server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastify-logs
    # pipeline_stages:
    #   - json:
    #       expressions:
    #         log: |-
    #           {"log": "%{message}"}
    static_configs:
      - targets:
          - fastify-basic:3002 # Adjust the address and port to match your Fastify application
        labels:
          job: fastify-logs
          __path__: /usr/fastify-logs/data/*.log
