name: Docker Build and Push Image

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    tags: [v*]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test various Github variables
        run: echo ${{ github.repository.tags }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: asdutoit/fastify-basic
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-kubernetes-yaml-files:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Kubernetes YAML files
        uses: Charlyzzz/update-k8s-image
        with:
          manifest-path: "kubernetes/fastify/environments/dev/fastify-basic/deployment.yml"
          new-image-tag: ${{ needs.build-and-push-image.outputs.tags }}
          container-name: fastify-basic
