kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  namespace: observability
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
